name: build-release

on:
  push:
    tags:
    - 'v*.*'

jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: build
      run: sudo make

    - name: release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          release-*
